from Config import few_shot_config

if few_shot_config["use_quartiles"]:
        prompts = [
        [
            ( # fixed prompt
                "system","""You are tasked with rating the originality of solutions to this creative problem-solving task: {problem}

    These solutions were generated by college students in a psychology experiment.

    When assessing originality, consider three key aspects: Novelty, Imagination, and Structure. Novelty refers to how unique the approach is compared to typical solutions. Imagination considers how creative and inventive the idea is. Structure examines whether the idea is limited by the scenario as presented, or if it questions assumptions and demonstrates out-of-the-box thinking.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that originality is independent from quality - a solution can be highly original but low in quality, or vice versa.

    Use a five-point scale for rating, where:
    0 is Very Unoriginal (very simple and/or common idea)
    1 is Unoriginal (simple idea, not novel or imaginative, structured by the scenario)
    2 is Original (shows some novelty and imagination, less structured by the problem)
    3 is Very Original (unique, novel, imaginative, and not structured by the scenario)

    Here are some example responses and their originality ratings to guide your rating:

    {examples}

    For the given solution, provide only a 0-4 originality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n"),
        ],
        [  # ooi fixed prompt
            ("system","""You are tasked with rating the originality of solutions to this creative problem-solving task: {heldout_problem}. 
            
    These solutions were generated by college students in a psychology experiment.

    When assessing originality, consider three key aspects: Novelty, Imagination, and Structure. Novelty refers to how unique the approach is compared to typical solutions. Imagination considers how creative and inventive the idea is. Structure examines whether the idea is limited by the scenario as presented, or if it questions assumptions and demonstrates out-of-the-box thinking.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that originality is independent from quality - a solution can be highly original but low in quality, or vice versa.

    Use a five-point scale for rating, where:
    0 is Very Unoriginal (very simple and/or common idea)
    1 is Unoriginal (simple idea, not novel or imaginative, structured by the scenario)
    2 is Original (shows some novelty and imagination, less structured by the problem)
    3 is Very Original (unique, novel, imaginative, and not structured by the scenario)


    Here are some example responses and their originality ratings to guide your rating:

    Problem: 
    {train_problem} 

    ###
    Responses:
    {examples}

    For the given solution, provide only a 0-4 originality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n")
        ],
        [ # oor quality
            ( 
                "system","""You are tasked with rating the quality of solutions to this creative problem-solving task: {problem}. 

    These solutions were generated by college students in a psychology experiment.

    When assessing quality, consider two key aspects: Completeness and Effectiveness. Completeness refers to how well the solution addresses multiple issues raised by the problem. Effectiveness examines whether the solution is viable, feasible, practical, or appropriate.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that quality is independent from originality - a solution can be high in quality but low in originality, or vice versa.

    Use five-point scale for rating, where:
    0 is Very Low Quality (solution incomplete, minimum effort)
    1 is Low Quality (simplistic solution, no elaboration, addresses only one point/issue or is probably not feasible)
    2 is High Quality (solution addresses 2 or more issues in the problem and is effective in addressing one and at least reasonably effective in addressing the other)
    3 is Very High Quality (solution addresses 2 or more issues and is effective in addressing all)

    Here are some example responses and their quality ratings to guide your rating: 

    {examples}

    For the given solution, provide only a 0-4 quality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n"),
        ],
        [
            # ooi quality
            ( 
                "system","""You are tasked with rating the quality of solutions to this creative problem-solving task: {heldout_problem}. 

    These solutions were generated by college students in a psychology experiment.

    When assessing quality, consider two key aspects: Completeness and Effectiveness. Completeness refers to how well the solution addresses multiple issues raised by the problem. Effectiveness examines whether the solution is viable, feasible, practical, or appropriate.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that quality is independent from originality - a solution can be high in quality but low in originality, or vice versa.

    Use five-point scale for rating, where:
    0 is Very Low Quality (solution incomplete, minimum effort)
    1 is Low Quality (simplistic solution, no elaboration, addresses only one point/issue or is probably not feasible)
    2 is High Quality (solution addresses 2 or more issues in the problem and is effective in addressing one and at least reasonably effective in addressing the other)
    3 is Very High Quality (solution addresses 2 or more issues and is effective in addressing all)

    Here are some example responses and their quality ratings to guide your rating: 

    Problem: 
    {train_problem} 

    ###
    Responses:
    {examples}

    For the given solution, provide only a 0-4 quality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n"),
        ]
    ]
else:
    prompts = [
        [
            ( # fixed prompt
                "system","""You are tasked with rating the originality of solutions to this creative problem-solving task: {problem}

    These solutions were generated by college students in a psychology experiment.

    When assessing originality, consider three key aspects: Novelty, Imagination, and Structure. Novelty refers to how unique the approach is compared to typical solutions. Imagination considers how creative and inventive the idea is. Structure examines whether the idea is limited by the scenario as presented, or if it questions assumptions and demonstrates out-of-the-box thinking.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that originality is independent from quality - a solution can be highly original but low in quality, or vice versa.

    Use a four-point scale for rating, where:
    0 is Very Unoriginal (very simple and/or common idea)
    1 is Unoriginal (simple idea, not novel or imaginative, structured by the scenario)
    2 is Neutral (limited novelty or imagination, still structured by the scenario)
    3 is Original (shows novelty and imagination, less structured by the problem)

    Here are some example responses and their originality ratings to guide your rating:

    {examples}

    For the given solution, provide only a 0-3 originality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n"),
        ],
        [  # ooi fixed prompt
            ("system","""You are tasked with rating the originality of solutions to this creative problem-solving task: {heldout_problem}. 
            
    These solutions were generated by college students in a psychology experiment.

    When assessing originality, consider three key aspects: Novelty, Imagination, and Structure. Novelty refers to how unique the approach is compared to typical solutions. Imagination considers how creative and inventive the idea is. Structure examines whether the idea is limited by the scenario as presented, or if it questions assumptions and demonstrates out-of-the-box thinking.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that originality is independent from quality - a solution can be highly original but low in quality, or vice versa.

    Use a four-point scale for rating, where:
    0 is Very Unoriginal (very simple and/or common idea)
    1 is Unoriginal (simple idea, not novel or imaginative, structured by the scenario)
    2 is Neutral (limited novelty or imagination, still structured by the scenario)
    3 is Original (shows novelty and imagination, less structured by the problem)


    Here are some example responses and their originality ratings to guide your rating:

    Problem: 
    {train_problem} 

    ###
    Responses:
    {examples}

    For the given solution, provide only a 0-3 originality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n")
        ],
        [ # oor quality
            ( 
                "system","""You are tasked with rating the quality of solutions to this creative problem-solving task: {problem}. 

    These solutions were generated by college students in a psychology experiment.

    When assessing quality, consider two key aspects: Completeness and Effectiveness. Completeness refers to how well the solution addresses multiple issues raised by the problem. Effectiveness examines whether the solution is viable, feasible, practical, or appropriate.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that quality is independent from originality - a solution can be high in quality but low in originality, or vice versa.

    Use four-point scale for rating, where:
    0 is Very Low Quality (solution incomplete, minimum effort)
    1 is Low Quality (simplistic solution, no elaboration, addresses only one point/issue or is probably not feasible)
    2 is Average Quality (solution tries to address more than one issue/point, but does so poorly, or with minimum elaboration)
    3 is High Quality (solution addresses 2 or more issues in the problem and is effective in addressing one and at least reasonably effective in addressing the other)

    Here are some example responses and their quality ratings to guide your rating: 

    {examples}

    For the given solution, provide only a 0-3 quality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n"),
        ],
        [
            # ooi quality
            ( 
                "system","""You are tasked with rating the quality of solutions to this creative problem-solving task: {heldout_problem}. 

    These solutions were generated by college students in a psychology experiment.

    When assessing quality, consider two key aspects: Completeness and Effectiveness. Completeness refers to how well the solution addresses multiple issues raised by the problem. Effectiveness examines whether the solution is viable, feasible, practical, or appropriate.

    Rate the solution as one in its totality, even if there are multiple parts or ideas. Do not "read into" the idea or assume intentions - rate based solely on what is written. Remember that quality is independent from originality - a solution can be high in quality but low in originality, or vice versa.

    Use four-point scale for rating, where:
    0 is Very Low Quality (solution incomplete, minimum effort)
    1 is Low Quality (simplistic solution, no elaboration, addresses only one point/issue or is probably not feasible)
    2 is Average Quality (solution tries to address more than one issue/point, but does so poorly, or with minimum elaboration)
    3 is High Quality (solution addresses 2 or more issues in the problem and is effective in addressing one and at least reasonably effective in addressing the other)

    Here are some example responses and their quality ratings to guide your rating: 

    Problem: 
    {train_problem} 

    ###
    Responses:
    {examples}

    For the given solution, provide only a 0-3 quality rating. Do not explain your rating or provide any additional commentary.""",),
            ("human", "{exemplar}\n"),
        ]
    ]